version: '2'
services:
    indikatorgwi-app:
        image: indikatorgwi
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://indikatorgwi-postgresql:5432/IndikatorGWI
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8383:8383
    indikatorgwi-postgresql:
        extends:
            file: postgresql.yml
            service: indikatorgwi-postgresql
